// Package storage keeps uploaded files (school logos). Callers use the Store
// interface only, so local disk can later be swapped for S3 or MinIO by adding
// another implementation and changing STORAGE_DRIVER; no handler changes.
package storage

import (
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"regexp"
	"strings"
)

// ErrNotFound is returned by Open and Delete for a key that does not exist.
var ErrNotFound = errors.New("storage: file not found")

// Store saves and reads files by key. Keys are generated by the server, never
// taken from a client: lower-case letters, digits, '-', '_', '.' and '/' between
// path segments, e.g. "logos/3f2a….png".
type Store interface {
	Put(ctx context.Context, key string, data []byte) error
	Open(ctx context.Context, key string) (io.ReadCloser, error)
	Delete(ctx context.Context, key string) error
}

var keyRe = regexp.MustCompile(`^[a-z0-9_-]+(/[a-z0-9_-]+)*\.[a-z0-9]+$`)

// ValidKey reports whether key is a safe storage key (no "..", no absolute paths).
func ValidKey(key string) bool {
	return len(key) <= 200 && keyRe.MatchString(key) && path.Clean(key) == key
}

// Local stores files under one directory on disk. os.Root confines every
// operation to that directory, so a key can never escape it (symlinks included).
type Local struct {
	root *os.Root
}

// NewLocal creates dir if needed and opens it as the storage root.
func NewLocal(dir string) (*Local, error) {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return nil, fmt.Errorf("create upload dir: %w", err)
	}
	root, err := os.OpenRoot(dir)
	if err != nil {
		return nil, fmt.Errorf("open upload dir: %w", err)
	}
	return &Local{root: root}, nil
}

func (l *Local) Close() error { return l.root.Close() }

// Put writes the file atomically: a temporary file in the same directory, then rename.
func (l *Local) Put(_ context.Context, key string, data []byte) error {
	if !ValidKey(key) {
		return fmt.Errorf("storage: invalid key %q", key)
	}
	if dir := path.Dir(key); dir != "." {
		if err := l.root.MkdirAll(dir, 0o750); err != nil {
			return fmt.Errorf("storage: mkdir: %w", err)
		}
	}
	tmp := key + ".tmp-" + randomSuffix()
	f, err := l.root.OpenFile(tmp, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o640)
	if err != nil {
		return fmt.Errorf("storage: create: %w", err)
	}
	_, werr := f.Write(data)
	if werr == nil {
		werr = f.Sync()
	}
	if cerr := f.Close(); werr == nil {
		werr = cerr
	}
	if werr == nil {
		werr = l.root.Rename(tmp, key)
	}
	if werr != nil {
		_ = l.root.Remove(tmp)
		return fmt.Errorf("storage: write: %w", werr)
	}
	return nil
}

func (l *Local) Open(_ context.Context, key string) (io.ReadCloser, error) {
	if !ValidKey(key) {
		return nil, ErrNotFound
	}
	f, err := l.root.Open(key)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("storage: open: %w", err)
	}
	return f, nil
}

func (l *Local) Delete(_ context.Context, key string) error {
	if !ValidKey(key) {
		return ErrNotFound
	}
	err := l.root.Remove(key)
	if errors.Is(err, fs.ErrNotExist) {
		return ErrNotFound
	}
	if err != nil {
		return fmt.Errorf("storage: delete: %w", err)
	}
	return nil
}

// New returns the store selected by driver. Only "local" exists today.
func New(driver, dir string) (Store, error) {
	switch strings.ToLower(driver) {
	case "", "local":
		return NewLocal(dir)
	default:
		return nil, fmt.Errorf("storage: unknown STORAGE_DRIVER %q (supported: local)", driver)
	}
}
